CREATE TABLE wishlist(
    wishlist_id NUMBER(6, 0) GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER(6, 0) NOT NULL,
    PRIMARY KEY(wishlist_id),
    CONSTRAINT fk_wishist_user_id
        FOREIGN KEY(user_id)
        REFERENCES users(user_id)
);

CREATE TABLE product_from_wishlist(
    wishlist_id NUMBER(6, 0) NOT NULL,
    product_id NUMBER(6, 0) NOT NULL,
    CONSTRAINT fk_product_from_wishlist_wishlist_id
        FOREIGN KEY(wishlist_id)
            REFERENCES wishlist(wishlist_id),
    CONSTRAINT fk_product_from_wishlist_product_id
        FOREIGN KEY(product_id)
            REFERENCES products(product_id)

);

